name: easy_localization_multi
description: A loader for easy_localization package that merges data from multiple other loaders.
version: 0.2.0
repository: https://github.com/alexeyinkin/flutter-easy-localization-multi

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  collection: ^1.16.0
  easy_localization: ^3.0.7
  flutter: { sdk: flutter }

dev_dependencies:
  total_lints: ^3.4.0
