name: my_package
version: 0.1.0

environment:
  sdk: ^3.1.3
  flutter: '>=2.0.0'

dependencies:
  easy_localization: ^3.0.3
  flutter: { sdk: flutter }

dev_dependencies:
  total_lints: ^3.1.1

flutter:
  assets:
    - assets/translations/en.yaml
